#!/bin/sh

case `hostname` in
    donkeykong.*)
        echo starting
        for x in `seq 1 7` ; do
            for host in druid-0.xeno skiing-0.xeno moonraider-0.xeno ; do
                ssh root@$host /root/envoy/scripts/build-tree $x
            done
        done

    ;;

    druid-0 | skiing-0 | moonraider | moonraider-0)
        cd /mnt/9p || exit
        echo `hostname` $1
        DEPTH=$1 ~/envoy/scripts/ownership-tree.pl < ~/envoy/scripts/dirs.txt | grep -A 1 -B 1 migrate
    ;;

    *)
        echo what to do for `hostname`?
    ;;
esac
